feat: mwcc/register
midwayjs/mwcc pull request #8
Opened 2020-11-24 08:09 UTC by echosoar

2020-11-24 10:05 UTC, Lxxyx requested changes

2020-11-24 10:05 UTC, Lxxyx commented on src/register/utils.ts
> +export const findRoot = current => {
应该是当前运行目录下没有 tsconfig.json 就报错吧。一路 findRoot 上去可能会找到错的？

2020-11-24 10:05 UTC, Lxxyx commented on src/register/utils.ts
> +export const debug = (...args) => {
建议使用统一的 debug 模块

2020-11-24 10:05 UTC, Lxxyx commented on src/register/utils.ts
> +  const sourceMapLength =
没太看懂这个操作。。

2020-11-24 11:48 UTC, echosoar commented on src/register/index.ts
> +  require.extensions['.ts'] = (m: any, filename: string) => {
这个定义不清楚，我翻了ts-node的代码里面写的也是any

2020-11-24 11:49 UTC, echosoar commented on src/register/utils.ts
> +  const sourceMapLength =
就是吧sourceMap追加到编译后的代码上，抄的ts-node ：https://github.com/TypeStrong/ts-node/blob/a7aa0af9aefae1a7d801bbfe969148866c852a5c/src/index.ts#L1172

2020-11-24 11:50 UTC, echosoar commented on src/register/utils.ts
> +  return ext !== '.ts' || /(?:^|\/)node_modules\//.test(filename);
tsx目前不在处理范围之内

2020-11-24 11:55 UTC, echosoar commented on src/register/utils.ts
> +export const findRoot = current => {
作为register应该是允许直接在src目录执行ts代码的，这个时候有两种处理方式：
1. 直接创建一个只带有sourceMap配置的compileOptions（ts-node采取的是这个），但是遇到paths这样的配置情况下会出错。
2. 去上层寻找，我认为在一个项目里面是应该存在tsconfig的，如果没有tsconfig，那就不是一个ts项目。

2020-11-24 11:57 UTC, Lxxyx commented on src/register/index.ts
> +  require.extensions['.ts'] = (m: any, filename: string) => {
m 的定义是 Module。可以看 @types/node

2020-11-25 03:26 UTC, Lxxyx requested changes

2020-11-25 03:26 UTC, Lxxyx commented on src/register/index.ts
> +const mwccDebug = debug('mwcc');
应该统一放在 util 里，然后所有地方都引用这个

2020-11-25 03:26 UTC, Lxxyx commented on src/register/utils.ts
> +export const findRoot = (current: string) => {
findRoot 的语义不明确，此处应该是 resoveTsConfig

2020-11-25 03:26 UTC, Lxxyx commented on src/register/utils.ts
> +export const findRoot = (current: string) => {
```suggestion
export const resolveTsConfig = (cwd: string) => {
```

2020-11-25 03:26 UTC, Lxxyx commented on src/util.ts
>  export function extend(...args) {
import 和下面的函数要空一行
```suggestion

export function extend(...args) {
```

2020-11-25 11:49 UTC, Lxxyx requested changes

2020-11-25 11:49 UTC, Lxxyx commented on test/register.test.ts
> +    setTimeout(() => {
用 Promise.race

2020-11-25 11:49 UTC, Lxxyx commented on test/register.test.ts
> +        child.stdout.on('data', data => {
fork 运行的子进程有异步的情况，on('data') 会触发多次。此处只拿了第一次。

2020-11-25 11:49 UTC, Lxxyx commented on src/program.ts
> +    const result = this.program.emit(
result 是无用变量

2020-11-25 11:49 UTC, Lxxyx commented on src/register/index.ts
> +const mwccDebug = debug('mwcc');
这个要换，把 mwcc 里所有 warn 都统一成 debug 的吧，不然和 https://github.com/midwayjs/mwcc/blob/master/src/logger.ts 有冲突

2020-11-25 11:49 UTC, Lxxyx commented on src/register/utils.ts
> +  const sourceMapLength =
需要加上引用的代码地址

2020-11-27 03:29 UTC, Lxxyx approved these changes

2020-11-27 06:33 UTC, legendecas commented on package.json
> +    "debug": "^4.3.1",
Node.js自带的 `util.debuglog` 可以用吧，没必要引入外部依赖吧

2020-11-27 06:35 UTC, legendecas commented on src/program.ts
> +        if (path.endsWith('.map')) {
dts 文件似乎没处理？

2020-11-27 06:36 UTC, legendecas commented on src/register/index.ts
> +  require.extensions['.ts'] = (m: any, filename: string) => {
这里有很多私有方法，Module 上不会暴露的（

2020-11-27 06:37 UTC, legendecas commented on src/register/utils.ts
> +  const sourceMapLength =
这种需要测试一下 tsconfig 里启用了 inlineSourcMap 的情况吧

2020-12-03 07:09 UTC, legendecas approved these changes

2020-12-03 07:10 UTC, merged